name: Build and publish

on:
    release:
      types: [published]

jobs:
  build-and-push:
    runs-on: windows-latest
    permissions:
      packages: write
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Extract release tag
        id: extract_release
        run: echo "RELEASE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install
      - name: Start build
        run: yarn publish
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}